[package]
name = "nanogui-rust-sdl"
version = "0.1.0"
authors = ["Michael de Lang <kingoipo@gmail.com>"]

[lib]
name = "nanoguirustsdl"
path = "src/mod.rs"

[dependencies]
sdl2 = "0.22"
sdl2-sys = "0.22"
nanovg = {version = "0.3.0", features = ["gl3"]}
